package vista;

import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import oruguita.Cliente;
import oruguita.Producto;
import oruguita.Proveedor;

/**
 *
 * @author ilich
 */
public class Menu extends javax.swing.JFrame {

    Cliente cl = new Cliente();
    Proveedor pr = new Proveedor();
    Producto pro = new Producto();
    DefaultTableModel modelo = new DefaultTableModel();

    public Menu() {
        initComponents();
        this.setLocationRelativeTo(null);
        txt_id_cliente.setVisible(false);
        txt_id_proveedor.setVisible(false);
        txt_id_producto.setVisible(false);
    }

    public void ListarCliente() {
        List<Cliente> ListaCl = cl.ListarCliente();
        modelo = (DefaultTableModel) table_cliente.getModel();
        Object[] ob = new Object[8];
        for (int i = 0; i < ListaCl.size(); i++) {
            ob[0] = ListaCl.get(i).getId();
            ob[1] = ListaCl.get(i).getRut();
            ob[2] = ListaCl.get(i).getNombre();
            ob[3] = ListaCl.get(i).getEdad();
            ob[4] = ListaCl.get(i).getSexo();
            ob[5] = ListaCl.get(i).getTelefono();
            ob[6] = ListaCl.get(i).getDireccion();
            ob[7] = ListaCl.get(i).getRazonSocial();
            modelo.addRow(ob);
        }
        table_cliente.setModel(modelo);
    }

    public void ListarProveedor() {
        List<Proveedor> ListaPr = pr.ListarProveedor();
        modelo = (DefaultTableModel) table_proveedor.getModel();
        Object[] ob = new Object[8];
        for (int i = 0; i < ListaPr.size(); i++) {
            ob[0] = ListaPr.get(i).getId();
            ob[1] = ListaPr.get(i).getRun();
            ob[2] = ListaPr.get(i).getNombre();
            ob[3] = ListaPr.get(i).getTelefono();
            ob[4] = ListaPr.get(i).getDireccion();
            ob[5] = ListaPr.get(i).getRegion();
            ob[6] = ListaPr.get(i).getRazonSocial();
            ob[7] = ListaPr.get(i).getTipoProducto();
            modelo.addRow(ob);
        }
        table_proveedor.setModel(modelo);
    }

    public void ListarProducto() {
        List<Producto> ListaPro = pro.ListarProducto();
        modelo = (DefaultTableModel) table_stock.getModel();
        Object[] ob = new Object[6];
        for (int i = 0; i < ListaPro.size(); i++) {
            ob[0] = ListaPro.get(i).getId();
            ob[1] = ListaPro.get(i).getCodigo();
            ob[2] = ListaPro.get(i).getDescripcion();
            ob[3] = ListaPro.get(i).getCantidad();
            ob[4] = ListaPro.get(i).getPrecio();
            ob[5] = ListaPro.get(i).getProveedor();
            modelo.addRow(ob);
        }
        table_stock.setModel(modelo);
    }

    public void LimpiarTable() {
        for (int i = 0; i < modelo.getRowCount(); i++) {
            modelo.removeRow(i);
            i = i - 1;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        Pnl_nuevaVenta = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btn_borrar_venta = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txt_descripcion_venta = new javax.swing.JTextField();
        txt_codigo_venta = new javax.swing.JTextField();
        txt_precio_venta = new javax.swing.JTextField();
        txt_cantidad_venta = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_venta = new javax.swing.JTable();
        btn_imprimir_venta = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_run_venta = new javax.swing.JTextField();
        txt_nombre_venta = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        txt_sexo_venta = new javax.swing.JTextField();
        txt_telefono_venta = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        txt_edad_venta = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        txt_direccion_venta = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        txt_razonSocial_venta = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        txt_formaPago = new javax.swing.JTextField();
        Pnl_cliente = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txt_razonSocial_cliente = new javax.swing.JTextField();
        txt_direccion_cliente = new javax.swing.JTextField();
        txt_telefono_cliente = new javax.swing.JTextField();
        txt_sexo_cliente = new javax.swing.JTextField();
        txt_edad_cliente = new javax.swing.JTextField();
        txt_nombre_cliente = new javax.swing.JTextField();
        txt_run_cliente = new javax.swing.JTextField();
        btn_guardar_cliente = new javax.swing.JButton();
        btn_actualizar_cliente = new javax.swing.JButton();
        btn_borrar_cliente = new javax.swing.JButton();
        btn_nuevo_cliente = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_cliente = new javax.swing.JTable();
        txt_id_cliente = new javax.swing.JTextField();
        Pnl_proveedor = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txt_run_proveedor = new javax.swing.JTextField();
        txt_nombre_proveedor = new javax.swing.JTextField();
        txt_telefono_proveedor = new javax.swing.JTextField();
        txt_direccion_proveedor = new javax.swing.JTextField();
        txt_razonSocial_proveedor = new javax.swing.JTextField();
        btn_guardar_proveedor = new javax.swing.JButton();
        btn_eliminar_proveedor = new javax.swing.JButton();
        btn_actualizar_proveedor = new javax.swing.JButton();
        btn_nuevo_proveedor = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        table_proveedor = new javax.swing.JTable();
        jLabel23 = new javax.swing.JLabel();
        txt_tipoProducto_proveedor = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        txt_region_proveedor = new javax.swing.JTextField();
        txt_id_proveedor = new javax.swing.JTextField();
        Pnl_stock = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        txt_codigo_producto = new javax.swing.JTextField();
        txt_descripcion_producto = new javax.swing.JTextField();
        txt_cantidad_producto = new javax.swing.JTextField();
        txt_precio_producto = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        table_stock = new javax.swing.JTable();
        btn_guardar_stock = new javax.swing.JButton();
        btn_actualizar_stock = new javax.swing.JButton();
        btn_eliminar_stock = new javax.swing.JButton();
        btn_nuevo_stock = new javax.swing.JButton();
        txt_id_producto = new javax.swing.JTextField();
        txt_proveedor_producto = new javax.swing.JTextField();
        Pnl_ventas = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        table_ventas = new javax.swing.JTable();
        btn_imprimir_ventas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setForeground(new java.awt.Color(102, 102, 255));

        jButton1.setBackground(new java.awt.Color(200, 150, 197));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/sell_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N
        jButton1.setText("Nueva Venta");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jButton2.setBackground(new java.awt.Color(200, 150, 197));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/face_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N
        jButton2.setText("Cliente");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(200, 150, 197));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/forklift_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N
        jButton3.setText("Proveedor");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(200, 150, 197));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/inventory_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N
        jButton4.setText("Producto");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(200, 150, 197));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/storefront_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N
        jButton5.setText("Ventas");
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Logo para java.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel1)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(45, 45, 45)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(200, 150, 197));
        jPanel2.setForeground(new java.awt.Color(200, 150, 197));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 257, Short.MAX_VALUE)
        );

        jTabbedPane1.setForeground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setToolTipText("");
        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTabbedPane1.setName(""); // NOI18N

        Pnl_nuevaVenta.setToolTipText("");
        Pnl_nuevaVenta.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Pnl_nuevaVenta.setFocusTraversalPolicyProvider(true);
        Pnl_nuevaVenta.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                Pnl_nuevaVentaAncestorMoved(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLabel2.setText("Codigo");

        jLabel3.setText("Cantidad");

        jLabel4.setText("Precio");

        btn_borrar_venta.setBackground(new java.awt.Color(255, 0, 0));
        btn_borrar_venta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/delete_forever_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N
        btn_borrar_venta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel6.setText("Descripcion");

        txt_codigo_venta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_codigo_ventaActionPerformed(evt);
            }
        });
        txt_codigo_venta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_codigo_ventaKeyPressed(evt);
            }
        });

        txt_precio_venta.setEditable(false);

        table_venta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Descripcion", "Cantidad", "Precio", "Total"
            }
        ));
        jScrollPane1.setViewportView(table_venta);
        if (table_venta.getColumnModel().getColumnCount() > 0) {
            table_venta.getColumnModel().getColumn(0).setPreferredWidth(30);
            table_venta.getColumnModel().getColumn(1).setPreferredWidth(100);
            table_venta.getColumnModel().getColumn(2).setPreferredWidth(30);
            table_venta.getColumnModel().getColumn(3).setPreferredWidth(30);
            table_venta.getColumnModel().getColumn(4).setPreferredWidth(40);
        }

        btn_imprimir_venta.setBackground(new java.awt.Color(200, 150, 197));
        btn_imprimir_venta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/print_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N
        btn_imprimir_venta.setToolTipText("");
        btn_imprimir_venta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_imprimir_venta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_imprimir_ventaActionPerformed(evt);
            }
        });

        jLabel7.setText("RUN");

        jLabel8.setText("Nombre");

        txt_run_venta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_run_ventaActionPerformed(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/payments_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N
        jLabel9.setText("TOTAL A PAGAR");

        jLabel10.setText("----------------------");

        jLabel30.setText("Sexo");

        jLabel31.setText("Telefono");

        jLabel32.setText("Edad");

        jLabel33.setText("Direccion");

        jLabel34.setText("Razon Social");

        jLabel35.setText("Forma de Pago");

        javax.swing.GroupLayout Pnl_nuevaVentaLayout = new javax.swing.GroupLayout(Pnl_nuevaVenta);
        Pnl_nuevaVenta.setLayout(Pnl_nuevaVentaLayout);
        Pnl_nuevaVentaLayout.setHorizontalGroup(
            Pnl_nuevaVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pnl_nuevaVentaLayout.createSequentialGroup()
                .addGroup(Pnl_nuevaVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Pnl_nuevaVentaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(Pnl_nuevaVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(Pnl_nuevaVentaLayout.createSequentialGroup()
                                .addGroup(Pnl_nuevaVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(txt_codigo_venta, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(32, 32, 32)
                                .addGroup(Pnl_nuevaVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(txt_descripcion_venta, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(Pnl_nuevaVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel35)
                                    .addComponent(txt_formaPago, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                                .addGroup(Pnl_nuevaVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(txt_cantidad_venta, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(61, 61, 61)
                                .addGroup(Pnl_nuevaVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(txt_precio_venta, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(179, 179, 179)
                                .addComponent(btn_borrar_venta, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(Pnl_nuevaVentaLayout.createSequentialGroup()
                        .addGroup(Pnl_nuevaVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Pnl_nuevaVentaLayout.createSequentialGroup()
                                .addGroup(Pnl_nuevaVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_run_venta, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(80, 80, 80)
                                .addGroup(Pnl_nuevaVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel31)
                                    .addComponent(txt_nombre_venta, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                                    .addComponent(txt_telefono_venta)))
                            .addComponent(jLabel30)
                            .addComponent(txt_sexo_venta, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(Pnl_nuevaVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel32)
                            .addComponent(txt_edad_venta)
                            .addComponent(jLabel33)
                            .addComponent(txt_direccion_venta, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(btn_imprimir_venta, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(Pnl_nuevaVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Pnl_nuevaVentaLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel34)
                            .addComponent(txt_razonSocial_venta, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        Pnl_nuevaVentaLayout.setVerticalGroup(
            Pnl_nuevaVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pnl_nuevaVentaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Pnl_nuevaVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_borrar_venta, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                    .addGroup(Pnl_nuevaVentaLayout.createSequentialGroup()
                        .addGroup(Pnl_nuevaVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel35, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(Pnl_nuevaVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addComponent(jLabel6)))
                        .addGap(18, 18, 18)
                        .addGroup(Pnl_nuevaVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_precio_venta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_cantidad_venta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_formaPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_descripcion_venta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_codigo_venta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 15, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Pnl_nuevaVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Pnl_nuevaVentaLayout.createSequentialGroup()
                        .addGroup(Pnl_nuevaVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_imprimir_venta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Pnl_nuevaVentaLayout.createSequentialGroup()
                                .addGroup(Pnl_nuevaVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel32))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(Pnl_nuevaVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_run_venta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_nombre_venta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_edad_venta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(Pnl_nuevaVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel30)
                                    .addComponent(jLabel31)
                                    .addComponent(jLabel33))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(Pnl_nuevaVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_sexo_venta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_telefono_venta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_direccion_venta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 10, Short.MAX_VALUE))
                    .addGroup(Pnl_nuevaVentaLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(Pnl_nuevaVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel34)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_razonSocial_venta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(12, Short.MAX_VALUE))))
        );

        jTabbedPane1.addTab("Nueva Venta", new javax.swing.ImageIcon(getClass().getResource("/imagenes/sell_FILL0_wght400_GRAD0_opsz24.png")), Pnl_nuevaVenta, ""); // NOI18N
        Pnl_nuevaVenta.getAccessibleContext().setAccessibleName("");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("RUN:");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("Nombre:");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setText("Edad:");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setText("Sexo:");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setText("Telefono:");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setText("Direccion:");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setText("Razon Social:");

        txt_sexo_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_sexo_clienteActionPerformed(evt);
            }
        });

        txt_nombre_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombre_clienteActionPerformed(evt);
            }
        });

        btn_guardar_cliente.setBackground(new java.awt.Color(51, 255, 51));
        btn_guardar_cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/save_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N
        btn_guardar_cliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_guardar_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardar_clienteActionPerformed(evt);
            }
        });

        btn_actualizar_cliente.setBackground(new java.awt.Color(51, 153, 255));
        btn_actualizar_cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/update_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N
        btn_actualizar_cliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_actualizar_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actualizar_clienteActionPerformed(evt);
            }
        });

        btn_borrar_cliente.setBackground(new java.awt.Color(204, 0, 51));
        btn_borrar_cliente.setForeground(new java.awt.Color(204, 0, 51));
        btn_borrar_cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/delete_forever_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N
        btn_borrar_cliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_borrar_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_borrar_clienteActionPerformed(evt);
            }
        });

        btn_nuevo_cliente.setBackground(new java.awt.Color(255, 255, 255));
        btn_nuevo_cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cleaning_services_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N
        btn_nuevo_cliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_nuevo_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nuevo_clienteActionPerformed(evt);
            }
        });

        table_cliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "RUN", "Nombre", "Edad", "Sexo", "Telefono", "Direccion", "Razon Social"
            }
        ));
        table_cliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_clienteMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table_cliente);
        if (table_cliente.getColumnModel().getColumnCount() > 0) {
            table_cliente.getColumnModel().getColumn(0).setPreferredWidth(35);
            table_cliente.getColumnModel().getColumn(1).setPreferredWidth(100);
            table_cliente.getColumnModel().getColumn(2).setPreferredWidth(100);
            table_cliente.getColumnModel().getColumn(3).setPreferredWidth(50);
            table_cliente.getColumnModel().getColumn(4).setPreferredWidth(50);
            table_cliente.getColumnModel().getColumn(5).setPreferredWidth(100);
            table_cliente.getColumnModel().getColumn(6).setPreferredWidth(100);
            table_cliente.getColumnModel().getColumn(7).setPreferredWidth(100);
        }

        javax.swing.GroupLayout Pnl_clienteLayout = new javax.swing.GroupLayout(Pnl_cliente);
        Pnl_cliente.setLayout(Pnl_clienteLayout);
        Pnl_clienteLayout.setHorizontalGroup(
            Pnl_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pnl_clienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Pnl_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Pnl_clienteLayout.createSequentialGroup()
                        .addGroup(Pnl_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_borrar_cliente, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                            .addComponent(btn_guardar_cliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(Pnl_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_actualizar_cliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_nuevo_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(Pnl_clienteLayout.createSequentialGroup()
                        .addGroup(Pnl_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel16)
                            .addComponent(jLabel15)
                            .addComponent(jLabel14)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11))
                        .addGap(11, 11, 11)
                        .addGroup(Pnl_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_razonSocial_cliente, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                            .addComponent(txt_direccion_cliente)
                            .addComponent(txt_telefono_cliente)
                            .addComponent(txt_sexo_cliente)
                            .addComponent(txt_edad_cliente)
                            .addComponent(txt_nombre_cliente)
                            .addComponent(txt_run_cliente)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Pnl_clienteLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txt_id_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 801, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        Pnl_clienteLayout.setVerticalGroup(
            Pnl_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pnl_clienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Pnl_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Pnl_clienteLayout.createSequentialGroup()
                        .addGroup(Pnl_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11)
                            .addComponent(txt_run_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(Pnl_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12)
                            .addComponent(txt_nombre_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(Pnl_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(txt_edad_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(Pnl_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14)
                            .addComponent(txt_sexo_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(Pnl_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel15)
                            .addComponent(txt_telefono_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(Pnl_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel16)
                            .addComponent(txt_direccion_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(Pnl_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(txt_razonSocial_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_id_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Pnl_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_actualizar_cliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_guardar_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(Pnl_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_borrar_cliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_nuevo_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 134, Short.MAX_VALUE))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Cliente", Pnl_cliente);

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setText("RUN");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel19.setText("Nombre");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel20.setText("Telefono");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel21.setText("Direccion");

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel22.setText("Razon Social");

        txt_nombre_proveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombre_proveedorActionPerformed(evt);
            }
        });

        btn_guardar_proveedor.setBackground(new java.awt.Color(51, 255, 51));
        btn_guardar_proveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/save_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N
        btn_guardar_proveedor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_guardar_proveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardar_proveedorActionPerformed(evt);
            }
        });

        btn_eliminar_proveedor.setBackground(new java.awt.Color(204, 0, 51));
        btn_eliminar_proveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/delete_forever_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N
        btn_eliminar_proveedor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_eliminar_proveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminar_proveedorActionPerformed(evt);
            }
        });

        btn_actualizar_proveedor.setBackground(new java.awt.Color(51, 153, 255));
        btn_actualizar_proveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/update_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N
        btn_actualizar_proveedor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_actualizar_proveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actualizar_proveedorActionPerformed(evt);
            }
        });

        btn_nuevo_proveedor.setBackground(new java.awt.Color(255, 255, 255));
        btn_nuevo_proveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cleaning_services_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N
        btn_nuevo_proveedor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_nuevo_proveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nuevo_proveedorActionPerformed(evt);
            }
        });

        table_proveedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "RUN", "Nombre", "Telefono", "Direccion", "Region", "Razon Social", "Tipo Productos"
            }
        ));
        table_proveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_proveedorMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(table_proveedor);
        if (table_proveedor.getColumnModel().getColumnCount() > 0) {
            table_proveedor.getColumnModel().getColumn(0).setPreferredWidth(35);
            table_proveedor.getColumnModel().getColumn(1).setPreferredWidth(100);
            table_proveedor.getColumnModel().getColumn(2).setPreferredWidth(100);
            table_proveedor.getColumnModel().getColumn(3).setPreferredWidth(100);
            table_proveedor.getColumnModel().getColumn(4).setPreferredWidth(100);
            table_proveedor.getColumnModel().getColumn(5).setPreferredWidth(100);
            table_proveedor.getColumnModel().getColumn(6).setPreferredWidth(100);
            table_proveedor.getColumnModel().getColumn(7).setPreferredWidth(100);
        }

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel23.setText("Tipo Productos");

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel24.setText("Region");

        javax.swing.GroupLayout Pnl_proveedorLayout = new javax.swing.GroupLayout(Pnl_proveedor);
        Pnl_proveedor.setLayout(Pnl_proveedorLayout);
        Pnl_proveedorLayout.setHorizontalGroup(
            Pnl_proveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pnl_proveedorLayout.createSequentialGroup()
                .addGroup(Pnl_proveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Pnl_proveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(Pnl_proveedorLayout.createSequentialGroup()
                            .addGroup(Pnl_proveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel22)
                                .addComponent(jLabel23)
                                .addComponent(jLabel24)
                                .addComponent(jLabel21)
                                .addComponent(jLabel20)
                                .addComponent(jLabel19)
                                .addComponent(jLabel18))
                            .addGap(18, 18, 18)
                            .addGroup(Pnl_proveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txt_run_proveedor, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                                .addComponent(txt_nombre_proveedor)
                                .addComponent(txt_telefono_proveedor)
                                .addComponent(txt_direccion_proveedor)
                                .addComponent(txt_razonSocial_proveedor)
                                .addComponent(txt_tipoProducto_proveedor)
                                .addComponent(txt_region_proveedor)))
                        .addGroup(Pnl_proveedorLayout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(Pnl_proveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btn_guardar_proveedor, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                                .addComponent(btn_eliminar_proveedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(Pnl_proveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btn_nuevo_proveedor, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                .addComponent(btn_actualizar_proveedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(Pnl_proveedorLayout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(txt_id_proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 770, Short.MAX_VALUE))
        );
        Pnl_proveedorLayout.setVerticalGroup(
            Pnl_proveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pnl_proveedorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Pnl_proveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Pnl_proveedorLayout.createSequentialGroup()
                        .addGroup(Pnl_proveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(txt_run_proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(Pnl_proveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(txt_nombre_proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(Pnl_proveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(txt_telefono_proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(Pnl_proveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(txt_direccion_proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(Pnl_proveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(txt_region_proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(Pnl_proveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(txt_razonSocial_proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(Pnl_proveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(txt_tipoProducto_proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(txt_id_proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(Pnl_proveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_actualizar_proveedor, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                            .addComponent(btn_guardar_proveedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(34, 34, 34)
                        .addGroup(Pnl_proveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_nuevo_proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_eliminar_proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 589, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Proveedor", Pnl_proveedor);

        Pnl_stock.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel25.setText("Codigo");

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel26.setText("Descripcion");

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel27.setText("Cantidad");

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel28.setText("Precio");

        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel29.setText("Proveedor");

        txt_descripcion_producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_descripcion_productoActionPerformed(evt);
            }
        });

        table_stock.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Codigo", "Descripcion", "Cantidad", "Precio", "Proveedor"
            }
        ));
        table_stock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_stockMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(table_stock);
        if (table_stock.getColumnModel().getColumnCount() > 0) {
            table_stock.getColumnModel().getColumn(0).setPreferredWidth(35);
            table_stock.getColumnModel().getColumn(1).setPreferredWidth(100);
            table_stock.getColumnModel().getColumn(2).setPreferredWidth(100);
            table_stock.getColumnModel().getColumn(4).setPreferredWidth(100);
            table_stock.getColumnModel().getColumn(5).setPreferredWidth(100);
        }

        btn_guardar_stock.setBackground(new java.awt.Color(51, 255, 51));
        btn_guardar_stock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/save_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N
        btn_guardar_stock.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_guardar_stock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardar_stockActionPerformed(evt);
            }
        });

        btn_actualizar_stock.setBackground(new java.awt.Color(51, 153, 255));
        btn_actualizar_stock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/update_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N
        btn_actualizar_stock.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_actualizar_stock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actualizar_stockActionPerformed(evt);
            }
        });

        btn_eliminar_stock.setBackground(new java.awt.Color(204, 0, 51));
        btn_eliminar_stock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/delete_forever_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N
        btn_eliminar_stock.setBorder(null);
        btn_eliminar_stock.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_eliminar_stock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminar_stockActionPerformed(evt);
            }
        });

        btn_nuevo_stock.setBackground(new java.awt.Color(255, 255, 255));
        btn_nuevo_stock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cleaning_services_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N
        btn_nuevo_stock.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_nuevo_stock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nuevo_stockActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Pnl_stockLayout = new javax.swing.GroupLayout(Pnl_stock);
        Pnl_stock.setLayout(Pnl_stockLayout);
        Pnl_stockLayout.setHorizontalGroup(
            Pnl_stockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Pnl_stockLayout.createSequentialGroup()
                .addGroup(Pnl_stockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(Pnl_stockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(Pnl_stockLayout.createSequentialGroup()
                            .addGroup(Pnl_stockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel27)
                                .addComponent(jLabel26))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(Pnl_stockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txt_descripcion_producto, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                                .addComponent(txt_cantidad_producto)))
                        .addGroup(Pnl_stockLayout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(Pnl_stockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(Pnl_stockLayout.createSequentialGroup()
                                    .addGroup(Pnl_stockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel28)
                                        .addComponent(jLabel29))
                                    .addGap(16, 16, 16)
                                    .addGroup(Pnl_stockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(Pnl_stockLayout.createSequentialGroup()
                                            .addComponent(txt_proveedor_producto, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(0, 0, Short.MAX_VALUE))
                                        .addComponent(txt_precio_producto)))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Pnl_stockLayout.createSequentialGroup()
                                    .addGroup(Pnl_stockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Pnl_stockLayout.createSequentialGroup()
                                            .addComponent(jLabel25)
                                            .addGap(37, 37, 37)
                                            .addComponent(txt_codigo_producto, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Pnl_stockLayout.createSequentialGroup()
                                            .addGroup(Pnl_stockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(btn_eliminar_stock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btn_guardar_stock, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE))
                                            .addGap(18, 18, 18)
                                            .addGroup(Pnl_stockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(btn_actualizar_stock, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                                                .addComponent(btn_nuevo_stock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                    .addGap(0, 0, Short.MAX_VALUE)))))
                    .addGroup(Pnl_stockLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txt_id_producto, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 701, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        Pnl_stockLayout.setVerticalGroup(
            Pnl_stockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pnl_stockLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Pnl_stockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Pnl_stockLayout.createSequentialGroup()
                        .addGroup(Pnl_stockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(txt_codigo_producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(Pnl_stockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(txt_descripcion_producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(Pnl_stockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27)
                            .addComponent(txt_cantidad_producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(Pnl_stockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel28)
                            .addComponent(txt_precio_producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(Pnl_stockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel29)
                            .addComponent(txt_proveedor_producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addComponent(txt_id_producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(Pnl_stockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_actualizar_stock, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_guardar_stock, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(Pnl_stockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_eliminar_stock, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_nuevo_stock, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(139, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Producto", Pnl_stock);

        table_ventas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Cliente", "Vendedor", "TOTAL"
            }
        ));
        jScrollPane5.setViewportView(table_ventas);

        btn_imprimir_ventas.setBackground(new java.awt.Color(200, 150, 197));
        btn_imprimir_ventas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/print_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N
        btn_imprimir_ventas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout Pnl_ventasLayout = new javax.swing.GroupLayout(Pnl_ventas);
        Pnl_ventas.setLayout(Pnl_ventasLayout);
        Pnl_ventasLayout.setHorizontalGroup(
            Pnl_ventasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pnl_ventasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Pnl_ventasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 1016, Short.MAX_VALUE)
                    .addGroup(Pnl_ventasLayout.createSequentialGroup()
                        .addComponent(btn_imprimir_ventas, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        Pnl_ventasLayout.setVerticalGroup(
            Pnl_ventasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pnl_ventasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_imprimir_ventas, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 533, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Ventas", Pnl_ventas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTabbedPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_codigo_ventaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_codigo_ventaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_codigo_ventaActionPerformed

    private void btn_imprimir_ventaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_imprimir_ventaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_imprimir_ventaActionPerformed

    private void txt_run_ventaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_run_ventaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_run_ventaActionPerformed

    private void Pnl_nuevaVentaAncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_Pnl_nuevaVentaAncestorMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_Pnl_nuevaVentaAncestorMoved

    private void txt_sexo_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_sexo_clienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_sexo_clienteActionPerformed

    private void txt_nombre_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombre_clienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombre_clienteActionPerformed

    private void btn_guardar_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardar_clienteActionPerformed
        if (!"".equals(txt_run_cliente.getText()) || !"".equals(txt_nombre_cliente.getText()) || !"".equals(txt_edad_cliente.getText()) || !"".equals(txt_sexo_cliente.getText()) || !"".equals(txt_telefono_cliente.getText()) || !"".equals(txt_direccion_cliente.getText()) || !"".equals(txt_razonSocial_cliente.getText()) || !"".equals(txt_direccion_cliente.getText())) {
            cl.setRut(txt_run_cliente.getText());
            cl.setNombre(txt_nombre_cliente.getText());
            cl.setEdad(Integer.parseInt(txt_edad_cliente.getText()));
            cl.setSexo(txt_sexo_cliente.getText());
            cl.setTelefono(Integer.parseInt(txt_telefono_cliente.getText()));
            cl.setDireccion(txt_direccion_cliente.getText());
            cl.setRazonSocial(txt_razonSocial_cliente.getText());
            cl.RegistrarCliente(cl);
            LimpiarTable();
            LimpiarCliente();
            ListarCliente();
            JOptionPane.showMessageDialog(null, "Cliente Registrado");
        } else {
            JOptionPane.showMessageDialog(null, "Campos vacios");
        }


    }//GEN-LAST:event_btn_guardar_clienteActionPerformed

    private void txt_nombre_proveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombre_proveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombre_proveedorActionPerformed

    private void btn_guardar_proveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardar_proveedorActionPerformed
        if (!"".equals(txt_run_proveedor.getText()) || !"".equals(txt_nombre_proveedor.getText()) || !"".equals(txt_telefono_proveedor.getText()) || !"".equals(txt_direccion_proveedor.getText()) || !"".equals(txt_region_proveedor.getText()) || !"".equals(txt_razonSocial_proveedor.getText()) || !"".equals(txt_tipoProducto_proveedor.getText())) {

            pr.setRun(txt_run_proveedor.getText());
            pr.setNombre(txt_nombre_proveedor.getText());
            pr.setTelefono(Integer.parseInt(txt_telefono_proveedor.getText()));
            pr.setDireccion(txt_direccion_proveedor.getText());
            pr.setRegion(txt_region_proveedor.getText());
            pr.setRazonSocial(txt_razonSocial_proveedor.getText());
            pr.setTipoProducto(txt_tipoProducto_proveedor.getText());
            pr.RegistrarProveedor(pr);
            JOptionPane.showMessageDialog(null, "Proveedor Registrado");

        } else {
            JOptionPane.showMessageDialog(null, "Campos vacios");

        }
    }//GEN-LAST:event_btn_guardar_proveedorActionPerformed

    private void btn_nuevo_proveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nuevo_proveedorActionPerformed
        LimpiarProveedor();       // TODO add your handling code here:
    }//GEN-LAST:event_btn_nuevo_proveedorActionPerformed

    private void txt_descripcion_productoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_descripcion_productoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_descripcion_productoActionPerformed

    private void btn_nuevo_stockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nuevo_stockActionPerformed
        LimpiarProducto();        // TODO add your handling code here:
    }//GEN-LAST:event_btn_nuevo_stockActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        LimpiarTable();
        ListarCliente();
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btn_actualizar_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actualizar_clienteActionPerformed
        if ("".equals(txt_id_cliente.getText())) {
            JOptionPane.showMessageDialog(null, "seleccione una fila");
        } else {

            if (!"".equals(txt_run_cliente.getText()) || !"".equals(txt_nombre_cliente.getText()) || !"".equals(txt_edad_cliente.getText()) || !"".equals(txt_sexo_cliente.getText()) || !"".equals(txt_telefono_cliente.getText()) || !"".equals(txt_direccion_cliente.getText()) || !"".equals(txt_razonSocial_cliente.getText()) || !"".equals(txt_direccion_cliente.getText())) {
                cl.setRut(txt_run_cliente.getText());
                cl.setNombre(txt_nombre_cliente.getText());
                cl.setEdad(Integer.parseInt(txt_edad_cliente.getText()));
                cl.setSexo(txt_sexo_cliente.getText());
                cl.setTelefono(Integer.parseInt(txt_telefono_cliente.getText()));
                cl.setDireccion(txt_direccion_cliente.getText());
                cl.setRazonSocial(txt_razonSocial_cliente.getText());
                cl.setId(Integer.parseInt(txt_id_cliente.getText()));
                cl.ModificarCliente(cl);
                LimpiarTable();
                LimpiarCliente();
                ListarCliente();
            } else {
                JOptionPane.showMessageDialog(null, "Los campos estan vacios");
            }

        }
    }//GEN-LAST:event_btn_actualizar_clienteActionPerformed

    private void table_clienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_clienteMouseClicked
        int fila = table_cliente.rowAtPoint(evt.getPoint());
        txt_id_cliente.setText(table_cliente.getValueAt(fila, 0).toString());
        txt_run_cliente.setText(table_cliente.getValueAt(fila, 1).toString());
        txt_nombre_cliente.setText(table_cliente.getValueAt(fila, 2).toString());
        txt_edad_cliente.setText(table_cliente.getValueAt(fila, 3).toString());
        txt_sexo_cliente.setText(table_cliente.getValueAt(fila, 4).toString());
        txt_telefono_cliente.setText(table_cliente.getValueAt(fila, 5).toString());
        txt_direccion_cliente.setText(table_cliente.getValueAt(fila, 6).toString());
        txt_razonSocial_cliente.setText(table_cliente.getValueAt(fila, 7).toString());


    }//GEN-LAST:event_table_clienteMouseClicked

    private void btn_borrar_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_borrar_clienteActionPerformed
        if (!"".equals(txt_id_cliente.getText())) {
            int pregunta = JOptionPane.showConfirmDialog(null, "¿Estas seguro de eliminar?");
            if (pregunta == 0) {
                int id = Integer.parseInt(txt_id_cliente.getText());
                cl.EliminarCliente(id);
                LimpiarTable();
                LimpiarCliente();
                ListarCliente();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione un cliente");
        }
    }//GEN-LAST:event_btn_borrar_clienteActionPerformed

    private void btn_nuevo_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nuevo_clienteActionPerformed
        LimpiarCliente();
    }//GEN-LAST:event_btn_nuevo_clienteActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        ListarProveedor();
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void table_proveedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_proveedorMouseClicked
        int fila = table_proveedor.rowAtPoint(evt.getPoint());
        txt_id_proveedor.setText(table_proveedor.getValueAt(fila, 0).toString());
        txt_run_proveedor.setText(table_proveedor.getValueAt(fila, 1).toString());
        txt_nombre_proveedor.setText(table_proveedor.getValueAt(fila, 2).toString());
        txt_telefono_proveedor.setText(table_proveedor.getValueAt(fila, 3).toString());
        txt_direccion_proveedor.setText(table_proveedor.getValueAt(fila, 4).toString());
        txt_region_proveedor.setText(table_proveedor.getValueAt(fila, 5).toString());
        txt_razonSocial_proveedor.setText(table_proveedor.getValueAt(fila, 6).toString());
        txt_tipoProducto_proveedor.setText(table_proveedor.getValueAt(fila, 7).toString());
    }//GEN-LAST:event_table_proveedorMouseClicked

    private void btn_eliminar_proveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminar_proveedorActionPerformed
        if (!"".equals(txt_id_proveedor.getText())) {
            int pregunta = JOptionPane.showConfirmDialog(null, "¿Estas seguro de eliminar?");
            if (pregunta == 0) {
                int id = Integer.parseInt(txt_id_proveedor.getText());
                pr.EliminarProveedor(id);
                LimpiarTable();
                ListarProveedor();
                LimpiarProveedor();

            }
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione un proveedor");
        }
    }//GEN-LAST:event_btn_eliminar_proveedorActionPerformed

    private void btn_actualizar_proveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actualizar_proveedorActionPerformed
        if ("".equals(txt_id_proveedor.getText())) {
            JOptionPane.showMessageDialog(null, "seleccione una fila");
        } else {

            if (!"".equals(txt_run_proveedor.getText()) || !"".equals(txt_nombre_proveedor.getText()) || !"".equals(txt_telefono_proveedor.getText()) || !"".equals(txt_direccion_proveedor.getText()) || !"".equals(txt_region_proveedor.getText()) || !"".equals(txt_razonSocial_proveedor.getText()) || !"".equals(txt_tipoProducto_proveedor.getText())) {
                pr.setRun(txt_run_proveedor.getText());
                pr.setNombre(txt_nombre_proveedor.getText());
                pr.setTelefono(Integer.parseInt(txt_telefono_proveedor.getText()));
                pr.setDireccion(txt_direccion_proveedor.getText());
                pr.setRegion(txt_region_proveedor.getText());
                pr.setRazonSocial(txt_razonSocial_proveedor.getText());
                pr.setTipoProducto(txt_tipoProducto_proveedor.getText());
                pr.setId(Integer.parseInt(txt_id_proveedor.getText()));
                pr.ModificarProveedor(pr);
                LimpiarTable();
                LimpiarProveedor();
                ListarProveedor();
            } else {
                JOptionPane.showMessageDialog(null, "Los campos estan vacios");
            }

        }
    }//GEN-LAST:event_btn_actualizar_proveedorActionPerformed

    private void btn_guardar_stockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardar_stockActionPerformed
        if (!"".equals(txt_codigo_producto.getText()) || !"".equals(txt_descripcion_producto.getText()) || !"".equals(txt_cantidad_producto.getText()) || !"".equals(txt_precio_producto.getText()) || !"".equals(txt_proveedor_producto.getText())) {

            pro.setCodigo(Integer.parseInt(txt_codigo_producto.getText()));
            pro.setDescripcion(txt_descripcion_producto.getText());
            pro.setCantidad(Integer.parseInt(txt_cantidad_producto.getText()));
            pro.setPrecio(Integer.parseInt(txt_precio_producto.getText()));
            pro.setProveedor(txt_proveedor_producto.getText());
            pro.RegistrarProducto(pro);
            JOptionPane.showMessageDialog(null, "Prodcuto Registrado");

        } else {
            JOptionPane.showMessageDialog(null, "Campos vacios");

        }

    }//GEN-LAST:event_btn_guardar_stockActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        ListarProducto();
        jTabbedPane1.setSelectedIndex(3);       // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void table_stockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_stockMouseClicked
        int fila = table_stock.rowAtPoint(evt.getPoint());
        txt_id_producto.setText(table_stock.getValueAt(fila, 0).toString());
        txt_codigo_producto.setText(table_stock.getValueAt(fila, 1).toString());
        txt_descripcion_producto.setText(table_stock.getValueAt(fila, 2).toString());
        txt_cantidad_producto.setText(table_stock.getValueAt(fila, 3).toString());
        txt_precio_producto.setText(table_stock.getValueAt(fila, 4).toString());
        txt_proveedor_producto.setText(table_stock.getValueAt(fila, 5).toString());


        // TODO add your handling code here:
    }//GEN-LAST:event_table_stockMouseClicked

    private void btn_eliminar_stockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminar_stockActionPerformed
        if (!"".equals(txt_id_producto.getText())) {
            int pregunta = JOptionPane.showConfirmDialog(null, "¿Estas seguro de eliminar?");

            if (pregunta == 0) {
                int id = Integer.parseInt(txt_id_producto.getText());
                pro.EliminarProducto(id);
                LimpiarTable();
                ListarProducto();
                LimpiarProducto();

            }
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione un producto");
        }
    }//GEN-LAST:event_btn_eliminar_stockActionPerformed

    private void btn_actualizar_stockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actualizar_stockActionPerformed
    if ("".equals(txt_id_producto.getText())) {
            JOptionPane.showMessageDialog(null, "seleccione una fila");
        } else {

            if (!"".equals(txt_codigo_producto.getText()) || !"".equals(txt_descripcion_producto.getText()) || !"".equals(txt_cantidad_producto.getText()) || !"".equals(txt_precio_producto.getText()) || !"".equals(txt_proveedor_producto.getText())) {
                pro.setCodigo(Integer.parseInt(txt_codigo_producto.getText()));
                pro.setDescripcion(txt_descripcion_producto.getText());
                pro.setCantidad(Integer.parseInt(txt_cantidad_producto.getText()));
                pro.setPrecio(Integer.parseInt(txt_precio_producto.getText()));
                pro.setProveedor(txt_proveedor_producto.getText()); 
                pro.setId(Integer.parseInt(txt_id_producto.getText()));                               
                pro.ModificarProducto(pro);
                LimpiarTable();
                LimpiarProducto();
                ListarProducto();
            } else {
                JOptionPane.showMessageDialog(null, "Los campos estan vacios");
            }

        }        // TODO add your handling code here:
    }//GEN-LAST:event_btn_actualizar_stockActionPerformed

    private void txt_codigo_ventaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_codigo_ventaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (!"".equals(txt_codigo_venta.getText())) {
                String cod = txt_codigo_venta.getText();
                pro = pro.BuscarPro(cod);
                if (pro.getDescripcion()!= null) {
                    txt_descripcion_venta.setText("" + pro.getDescripcion());
                    txt_precio_venta.setText("" + pro.getPrecio());
                    txt_cantidad_venta.setText("" + pro.getCantidad());
                    txt_cantidad_venta.requestFocus();
                } else {
                    LimparVenta();
                    txt_codigo_venta.requestFocus();
                }
            } else {
                JOptionPane.showMessageDialog(null, "Ingrese el codigo del productos");
                txt_codigo_venta.requestFocus();
            }
        }            // TODO add your handling code here:
    }//GEN-LAST:event_txt_codigo_ventaKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Pnl_cliente;
    private javax.swing.JPanel Pnl_nuevaVenta;
    private javax.swing.JPanel Pnl_proveedor;
    private javax.swing.JPanel Pnl_stock;
    private javax.swing.JPanel Pnl_ventas;
    private javax.swing.JButton btn_actualizar_cliente;
    private javax.swing.JButton btn_actualizar_proveedor;
    private javax.swing.JButton btn_actualizar_stock;
    private javax.swing.JButton btn_borrar_cliente;
    private javax.swing.JButton btn_borrar_venta;
    private javax.swing.JButton btn_eliminar_proveedor;
    private javax.swing.JButton btn_eliminar_stock;
    private javax.swing.JButton btn_guardar_cliente;
    private javax.swing.JButton btn_guardar_proveedor;
    private javax.swing.JButton btn_guardar_stock;
    private javax.swing.JButton btn_imprimir_venta;
    private javax.swing.JButton btn_imprimir_ventas;
    private javax.swing.JButton btn_nuevo_cliente;
    private javax.swing.JButton btn_nuevo_proveedor;
    private javax.swing.JButton btn_nuevo_stock;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable table_cliente;
    private javax.swing.JTable table_proveedor;
    private javax.swing.JTable table_stock;
    private javax.swing.JTable table_venta;
    private javax.swing.JTable table_ventas;
    private javax.swing.JTextField txt_cantidad_producto;
    private javax.swing.JTextField txt_cantidad_venta;
    private javax.swing.JTextField txt_codigo_producto;
    private javax.swing.JTextField txt_codigo_venta;
    private javax.swing.JTextField txt_descripcion_producto;
    private javax.swing.JTextField txt_descripcion_venta;
    private javax.swing.JTextField txt_direccion_cliente;
    private javax.swing.JTextField txt_direccion_proveedor;
    private javax.swing.JTextField txt_direccion_venta;
    private javax.swing.JTextField txt_edad_cliente;
    private javax.swing.JTextField txt_edad_venta;
    private javax.swing.JTextField txt_formaPago;
    private javax.swing.JTextField txt_id_cliente;
    private javax.swing.JTextField txt_id_producto;
    private javax.swing.JTextField txt_id_proveedor;
    private javax.swing.JTextField txt_nombre_cliente;
    private javax.swing.JTextField txt_nombre_proveedor;
    private javax.swing.JTextField txt_nombre_venta;
    private javax.swing.JTextField txt_precio_producto;
    private javax.swing.JTextField txt_precio_venta;
    private javax.swing.JTextField txt_proveedor_producto;
    private javax.swing.JTextField txt_razonSocial_cliente;
    private javax.swing.JTextField txt_razonSocial_proveedor;
    private javax.swing.JTextField txt_razonSocial_venta;
    private javax.swing.JTextField txt_region_proveedor;
    private javax.swing.JTextField txt_run_cliente;
    private javax.swing.JTextField txt_run_proveedor;
    private javax.swing.JTextField txt_run_venta;
    private javax.swing.JTextField txt_sexo_cliente;
    private javax.swing.JTextField txt_sexo_venta;
    private javax.swing.JTextField txt_telefono_cliente;
    private javax.swing.JTextField txt_telefono_proveedor;
    private javax.swing.JTextField txt_telefono_venta;
    private javax.swing.JTextField txt_tipoProducto_proveedor;
    // End of variables declaration//GEN-END:variables

    private void LimpiarCliente() {
        txt_id_cliente.setText("");
        txt_nombre_cliente.setText("");
        txt_run_cliente.setText("");
        txt_edad_cliente.setText("");
        txt_telefono_cliente.setText("");
        txt_direccion_cliente.setText("");
        txt_razonSocial_cliente.setText("");
        txt_sexo_cliente.setText("");

    }

    private void LimpiarProveedor() {
        txt_id_proveedor.setText("");
        txt_run_proveedor.setText("");
        txt_nombre_proveedor.setText("");
        txt_telefono_proveedor.setText("");
        txt_direccion_proveedor.setText("");
        txt_region_proveedor.setText("");
        txt_razonSocial_proveedor.setText("");
        txt_tipoProducto_proveedor.setText("");

    }

    private void LimpiarProducto() {
        txt_codigo_producto.setText("");
        txt_descripcion_producto.setText("");
        txt_cantidad_producto.setText("");
        txt_precio_producto.setText("");
        txt_proveedor_producto.setText("");
    }
    private void LimparVenta(){
        txt_codigo_venta.setText("");
        txt_descripcion_venta.setText("");
        txt_cantidad_venta.setText("");
        txt_precio_venta.setText("");
                
    }
}

